[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "database-remote"
version = "0.1.0"
description = "Database Remote Management tool"
authors = [
    {name = "wtalioy"},
]
requires-python = ">=3.10"
dependencies = [
    "pandas",
]