CREATE_DATABASE = "CREATE DATABASE {}" # name
USE_DATABASE = "USE {}" # name
DROP_DATABASE = "DROP DATABASE {}" # name
CREATE_TABLE = "CREATE TABLE IF NOT EXISTS {} ({})" # name, column_info
DROP_TABLE = "DROP TABLE {}" # name
WHERE = "WHERE {}" # condition
SELECT = "SELECT {} FROM {} {}" # column, tables, condition
INSERT = "INSERT INTO {} ({}) VALUES ({})" # table, column, value
UPDATE = "UPDATE {} SET {} {}" # table, column, condition
DELETE = "DELETE FROM {} {}" # table, condition
LIKE = "LIKE '{}'" # pattern
UNION = "{} UNION {}" # query1, query2
ORDER_BY = "ORDER BY {}" # column-option
GROUP_BY = "GROUP BY {}" # column
JOIN = "{} {} JOIN {} {}" # table1, option(NATURAL|LEFT|RIGHT), table2, condition
ADD_COLUMN = "ALTER TABLE {} ADD COLUMN {} {}" # name, column, datatype
DROP_COLUMN = "ALTER TABLE {} DROP COLUMN {}" # name, column
MODIFY_COLUMN = "ALTER TABLE {} MODIFY COLUMN {} {}" # name, column, datatype
RENAME_COLUMN = "ALTER TABLE {} CHANGE COLUMN {} {} {}" # name, old_name, new_name, datatype
ADD_PRIMARY_KEY = "ALTER TABLE {} ADD PRIMARY KEY ({})" # name, column
ADD_FOREIGN_KEY = "ALTER TABLE {} ADD FOREIGN KEY ({}) REFERENCES {} ({})" # name, column, table, column
RENAME_TABLE = "ALTER TABLE {} RENAME TO {}" # old_name, new_name